language: c

# use containers
sudo: false

addons:
  apt:
    sources:
    - r-packages-precise
    packages:
    - r-base-dev
    - r-recommended
    - pandoc
    - default-jdk
    - default-jre

# cache local R libraries directory:
cache:
  directories:
    - ~/Rlib

# install the package and dependencies:
install:
  - mkdir -p ~/Rlib
  - echo 'R_LIBS=~/Rlib' > .Renviron
  - echo 'options(repos = "http://cran.rstudio.com")' > .Rprofile
  - mkdir -p ~/.R
  - Rscript -e 'if(!"devtools" %in% rownames(installed.packages())) { install.packages("devtools", dependencies = TRUE) }'
  - Rscript -e 'if (!require("covr")) devtools::install_github("jimhester/covr")'
  - Rscript -e 'if (!require("drat")) install.packages("drat")'
  - Rscript -e 'if(!"rJava" %in% rownames(installed.packages())) { install.packages("rJava", dependencies = TRUE) }'
  - Rscript -e 'if(!"testthat" %in% rownames(installed.packages())) { install.packages("testthat", dependencies = TRUE) }'
  - Rscript -e 'if(!"knitr" %in% rownames(installed.packages())) { install.packages("knitr", dependencies = TRUE) }'
  - Rscript -e 'if(!"rmarkdown" %in% rownames(installed.packages())) { install.packages("rmarkdown", dependencies = TRUE) }'
  - Rscript -e 'if(!"RJDBC" %in% rownames(installed.packages())) { install.packages("RJDBC", dependencies = TRUE) }'
  - Rscript -e 'if(!"bit" %in% rownames(installed.packages())) { install.packages("bit", dependencies = TRUE) }'
  - Rscript -e 'if(!"ff" %in% rownames(installed.packages())) { install.packages("ff", dependencies = TRUE) }'
  - Rscript -e 'if(!"ffbase" %in% rownames(installed.packages())) { install.packages("ffbase", dependencies = TRUE) }'
  - Rscript -e 'if(!"plyr" %in% rownames(installed.packages())) { install.packages("plyr", dependencies = TRUE) }'
  - Rscript -e 'if(!"survival" %in% rownames(installed.packages())) { install.packages("survival", dependencies = TRUE) }'

  # Install OHDSI dependencies
  - Rscript -e 'devtools::install_github("OHDSI/SqlRender")'
  - Rscript -e 'devtools::install_github("OHDSI/DatabaseConnector")'
  - Rscript -e 'devtools::install_github("OHDSI/Cyclops")'
  - Rscript -e 'devtools::install_github("OHDSI/OhdsiRTools")'
  - Rscript -e 'devtools::install_github("OHDSI/FeatureExtraction")'
  - Rscript -e 'devtools::install_github("OHDSI/CaseControl")'

  - Rscript -e 'update.packages(ask = FALSE, instlib = "~/Rlib")'
  - Rscript -e 'devtools::install_deps(pkg = ".", dependencies = TRUE)'

before_script:
  - export PKG_NAME=$(Rscript -e 'cat(paste0(devtools::as.package(".")$package))')
  - export PKG_TARBALL=$(Rscript -e 'pkg <- devtools::as.package("."); cat(paste0(pkg$package,"_",pkg$version,".tar.gz"))')

# Build and check package
script:
  - R CMD build . --no-build-vignettes --no-manual
  - _R_CHECK_CRAN_INCOMING_=FALSE R CMD check "${PKG_TARBALL}" --no-build-vignettes --no-manual
  - cat ${PKG_NAME}.Rcheck/00install.out # Print out install / compile log

notifications:
  recipients:
    - msuchard@gmail.com
    - schuemie@ohdsi.org
  email:
    on_success: change
    on_failure: change

after_success:
  - Rscript -e 'library(covr);codecov()'
  
env:
  global:
    secure: X55qTaMj/Aars93tWGdE5WIef4KNLJpZwtBVEr+xFczZ3R/gHnrl/uqAjURAKeoDpf9lDoZ+np9q+rns7vav3NT7WThOl1oN+OoRh40JddozDwlEkuyNPX5kKB5N9vn8w5TdHz6PUYgS0xXpY2MYoTUIF1TAgdUn95tIAKU56sJ4BstbA2uG3ZzPz3R4JE9UdpnwARCfbzdH9tnMQfFIYT1aFdLFe2zMEwOr6WBaK+wOOgds5rG0W561eYz2CRvXFbowMCjm8AgK4/Ols9R7y3UXZNVtJLuYdcquUIH6zz4YzVIN+pchel7BvrUmRJnZvv1uCumadSjoyfKAgPLBogAnjtWDg/E9Z8waG1qIV/VPhEKAOHl22wQ+7wA5sTxRswOz6xKWiA+vpziLAgLbEsQ9rvExDiDdZlFnc9J+RLIojpw7k0TNltgIxAvrRFlJzirVHSbGCTBadDUJrMCKm0noddTEWuyl+P4/v9iyuhCHpqEb7fhFDkesAxfxdqQth2o7ZNhtQDq1FlLqzWYxHopSp0fgC1CnFKmYpzBYxMq/qcqy+EhucpmQReRZpMfsKoRo8NsbGRVPG6Ks3BWf7ghCl97JhRpim8kNV/215aSWr06vWShqE6IG6FH2TRQvj48pPXYPcBZFMcJ6r5eeWxWeY6eVMlsCOD3qQNwMKx0=
