# Copyright 2020 Observational Health Data Sciences and Informatics
#
# This file is part of CaseCrossover
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Format and check code
OhdsiRTools::formatRFolder()
OhdsiRTools::checkUsagePackage("CaseCrossover")
OhdsiRTools::updateCopyrightYearFolder()
devtools::spell_check()

# Create manual and vignette
unlink("extras/CaseCrossover.pdf")
shell("R CMD Rd2pdf ./ --output=extras/CaseCrossover.pdf")

rmarkdown::render("vignettes/SingleStudies.Rmd",
                  output_file = "../inst/doc/SingleStudies.pdf",
                  rmarkdown::pdf_document(latex_engine = "pdflatex",
                                          toc = TRUE,
                                          number_sections = TRUE))
unlink("inst/doc/SingleStudies.tex")

rmarkdown::render("vignettes/MultipleAnalyses.Rmd",
                  output_file = "../inst/doc/MultipleAnalyses.pdf",
                  rmarkdown::pdf_document(latex_engine = "pdflatex",
                                          toc = TRUE,
                                          number_sections = TRUE))
unlink("inst/doc/MultipleAnalyses.tex")

pkgdown::build_site()
OhdsiRTools::fixHadesLogo()

# Create arg functions:
library(CaseCrossover)
rCode <- c("# This file has been autogenerated. Do not change by hand. ")
rCode <- ParallelLogger::createArgFunction("getDbCaseCrossoverData",
                                        excludeArgs = c("connectionDetails",
                                                        "cdmDatabaseSchema",
                                                        "oracleTempSchema",
                                                        "outcomeDatabaseSchema",
                                                        "outcomeTable",
                                                        "outcomeIds",
                                                        "nestingCohortDatabaseSchema",
                                                        "nestingCohortTable",
                                                        "nestingCohortId",
                                                        "exposureDatabaseSchema",
                                                        "exposureTable",
                                                        "exposureIds"),
                                        rCode = rCode)
rCode <- ParallelLogger::createArgFunction("selectSubjectsToInclude",
                                        excludeArgs = c("caseCrossoverData", "outcomeId"),
                                        rCode = rCode)
rCode <- ParallelLogger::createArgFunction("getExposureStatus",
                                        excludeArgs = c("caseCrossoverData", "subjects", "exposureId"),
                                        rCode = rCode)
writeLines(rCode, "r/CreateArgFunctions.R")
OhdsiRTools::formatRFile("r/CreateArgFunctions.R")
